spring:
  datasource:
    url: jdbc:mysql://db-billige-server.cfqsq7cddhev.ap-northeast-2.rds.amazonaws.com:3306/Billige
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: billige
    password: billige2021!

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: billige2021@gmail.com
    password: wtfaceisoirtjmcg
    properties:
      mail:
        smtp:
          auth: true
          timeout: 3000
          starttls:
            enable: true